ASPNET04/Models/Item.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ASPNET04.Models
{
    public class Item
    {
        public Producto Producto { get; set; }
        public int Cantidad { get; set; }
    }
}

ASPNET04/Models/Producto.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ASPNET04.Models
{
    public class Producto
    {
        public string Id { get; set; }
        public string Nombre { get; set; }
        public double Precio { get; set; }
        public string Foto { get; set; }
    }
}

ASPNET04/Models/ProductoModelo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ASPNET04.Models
{

    public class ProductoModelo
    {
        private List<Producto> productos;
        public ProductoModelo() {
            productos = new List<Producto>() {
                new Producto {
                    Id = "prod01",
                    Nombre = "Nombre producto 01",
                    Precio = 23.5,
                    Foto = "p1.jpg"
                },
                new Producto {
                    Id = "prod02",
                    Nombre = "Nombre producto 02",
                    Precio = 54.7,
                    Foto = "p2.jpg"
                },
                new Producto {
                    Id = "prod03",
                    Nombre = "Nombre producto 03",
                    Precio = 10,
                    Foto = "p3.jpg"
                }
            };
        }
        public List<Producto> GetTodo() {
            return productos;
        }
        public Producto Get(string id) {
            return productos.Single(x => x.Id == id);
        }
    }
}

ASPNET04/Controllers/CarritoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ASPNET04.Models;

namespace ASPNET04.Controllers
{
    public class CarritoController : Controller
    {
        // GET: Carrito
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Compra(string id)
        {
            ProductoModelo prodM = new ProductoModelo();
            if (Session["carrito"] == null)
            {
                List<Item> carro = new List<Item>();
                carro.Add(new Item { Producto = prodM.Get(id), Cantidad = 1 });
                Session["carrito"] = carro;
            }
            else {
                List<Item> carro = (List<Item>)Session["carrito"];
                int indice = Existe(id);
                if (indice != -1) {
                    carro[indice].Cantidad++;
                }
                else
                {
                    carro.Add(new Item { Producto = prodM.Get(id), Cantidad = 1});
                }
                Session["carrito"] = carro;
            }
            return RedirectToAction("Index");
        }
        private int Existe(string id) {
            List<Item> carro = (List<Item>)Session["carrito"];
            for (int i = 0; i < carro.Count; i++) {
                if (carro[i].Producto.Id == id)
                    return i;
            }
            return -1;
        }
        public ActionResult Borrar(string id) {
            List<Item> carro = (List<Item>)Session["carrito"];
            int indice = Existe(id);
            carro.RemoveAt(indice);
            Session["carrito"] = carro;
            return RedirectToAction("Index");
        }
    }
}

ASPNET04/Controllers/ProductoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ASPNET04.Models;

namespace ASPNET04.Controllers
{
    public class ProductoController : Controller
    {
        // GET: Producto
        public ActionResult Index()
        {
            ProductoModelo prodModelo = new ProductoModelo();
            ViewBag.productos = prodModelo.GetTodo();
            return View();
        }
    }
}

ASPNET04/Views/Carrito/Index.cshtml
@{
    Layout = null;
}
@using ASPNET04.Models
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Carrito</title>
</head>
<body>
    <h3>Carrito</h3>
    <table>
        <tr>
            <td>Opción</td>
            <td>ID</td>
            <td>Nombre</td>
            <td>Precio</td>
            <td>Foto</td>
            <td>Cantidad</td>
            <td>Subtotal</td>
        </tr>
        @foreach (Item item in (List<Item>)Session["carrito"])
        {
            <td><a href="@Url.Action("Borrar", "Carrito", new { id = item.Producto.Id})">Borrar</a></td>
            <tr>
                <td>@(item.Producto.Precio * item.Cantidad)</td>
            </tr>        }
        <tr>
            <td>TOTAL:</td>
            <td>
                @{ 
                    List<Item> carro = (List<Item>)Session["carrito"];
                    var tot = carro.Sum(x => x.Producto.Precio * x.Cantidad);
                }
                @tot
            </td>
        </tr>
    </table>
</body>
</html>

ASPNET04/Views/Producto/Index.cshtml
@{
    Layout = null;
}
@using ASPNET04.Models
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <h3>LISTA DE PRODUCTOS</h3>
    <table>
        <tr>
            <td>ID</td>
            <td>Nombre</td>
            <td>Precio</td>
            <td>Foto</td>
            <td>COMPRAR</td>
        </tr>
        @foreach (Producto prod in ViewBag.productos) {
            <tr>
                <td>@prod.Id</td>
                <td>@prod.Nombre</td>
                <td>@prod.Precio</td>
                <td>@prod.Foto</td>
                <td>
                    <a href="@Url.Action("Compra", "Carrito", new { id = prod.Id})"></a>
                </td>
            </tr>
        }
    </table>
</body>
</html>